name: Lighthouse CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run LHCI (no PR comments on forks)
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
        run: npm run lhci

      - name: Run LHCI with PR comments
        if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
        run: npm run lhci
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}